// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: agenttask.proto

package agenttask

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListExistingTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Optional filter by task state (running, stopped, etc.)
	StateFilter string `protobuf:"bytes,1,opt,name=state_filter,json=stateFilter,proto3" json:"state_filter,omitempty"`
}

func (x *ListExistingTasksRequest) Reset() {
	*x = ListExistingTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agenttask_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListExistingTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExistingTasksRequest) ProtoMessage() {}

func (x *ListExistingTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agenttask_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExistingTasksRequest.ProtoReflect.Descriptor instead.
func (*ListExistingTasksRequest) Descriptor() ([]byte, []int) {
	return file_agenttask_proto_rawDescGZIP(), []int{0}
}

func (x *ListExistingTasksRequest) GetStateFilter() string {
	if x != nil {
		return x.StateFilter
	}
	return ""
}

type ExistingTaskInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Task ID as known by the container runtime
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Current state of the task (running, stopped, etc.)
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Process ID of the main container process
	Pid uint32 `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	// Additional metadata from container runtime
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ExistingTaskInfo) Reset() {
	*x = ExistingTaskInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agenttask_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistingTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistingTaskInfo) ProtoMessage() {}

func (x *ExistingTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agenttask_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistingTaskInfo.ProtoReflect.Descriptor instead.
func (*ExistingTaskInfo) Descriptor() ([]byte, []int) {
	return file_agenttask_proto_rawDescGZIP(), []int{1}
}

func (x *ExistingTaskInfo) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExistingTaskInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ExistingTaskInfo) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ExistingTaskInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListExistingTasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of existing tasks discovered from container runtime
	Tasks []*ExistingTaskInfo `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *ListExistingTasksResponse) Reset() {
	*x = ListExistingTasksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agenttask_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListExistingTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExistingTasksResponse) ProtoMessage() {}

func (x *ListExistingTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agenttask_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExistingTasksResponse.ProtoReflect.Descriptor instead.
func (*ListExistingTasksResponse) Descriptor() ([]byte, []int) {
	return file_agenttask_proto_rawDescGZIP(), []int{2}
}

func (x *ListExistingTasksResponse) GetTasks() []*ExistingTaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_agenttask_proto protoreflect.FileDescriptor

var file_agenttask_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3d, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x22, 0xcd, 0x01, 0x0a, 0x10, 0x45, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x3b, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x44, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a,
	0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x32, 0x57, 0x0a, 0x09, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x12, 0x4a, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x19, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x0d, 0x5a, 0x0b, 0x2e, 0x3b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x74, 0x61, 0x73, 0x6b, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agenttask_proto_rawDescOnce sync.Once
	file_agenttask_proto_rawDescData = file_agenttask_proto_rawDesc
)

func file_agenttask_proto_rawDescGZIP() []byte {
	file_agenttask_proto_rawDescOnce.Do(func() {
		file_agenttask_proto_rawDescData = protoimpl.X.CompressGZIP(file_agenttask_proto_rawDescData)
	})
	return file_agenttask_proto_rawDescData
}

var file_agenttask_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_agenttask_proto_goTypes = []interface{}{
	(*ListExistingTasksRequest)(nil),  // 0: ListExistingTasksRequest
	(*ExistingTaskInfo)(nil),          // 1: ExistingTaskInfo
	(*ListExistingTasksResponse)(nil), // 2: ListExistingTasksResponse
	nil,                               // 3: ExistingTaskInfo.MetadataEntry
}
var file_agenttask_proto_depIdxs = []int32{
	3, // 0: ExistingTaskInfo.metadata:type_name -> ExistingTaskInfo.MetadataEntry
	1, // 1: ListExistingTasksResponse.tasks:type_name -> ExistingTaskInfo
	0, // 2: AgentTask.ListExistingTasks:input_type -> ListExistingTasksRequest
	2, // 3: AgentTask.ListExistingTasks:output_type -> ListExistingTasksResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agenttask_proto_init() }
func file_agenttask_proto_init() {
	if File_agenttask_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agenttask_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListExistingTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agenttask_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistingTaskInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agenttask_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListExistingTasksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agenttask_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agenttask_proto_goTypes,
		DependencyIndexes: file_agenttask_proto_depIdxs,
		MessageInfos:      file_agenttask_proto_msgTypes,
	}.Build()
	File_agenttask_proto = out.File
	file_agenttask_proto_rawDesc = nil
	file_agenttask_proto_goTypes = nil
	file_agenttask_proto_depIdxs = nil
}
