// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: agenttask.proto
package agenttask

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type AgentTaskService interface {
	ListExistingTasks(context.Context, *ListExistingTasksRequest) (*ListExistingTasksResponse, error)
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
}

func RegisterAgentTaskService(srv *ttrpc.Server, svc AgentTaskService) {
	srv.RegisterService("AgentTask", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"ListExistingTasks": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ListExistingTasksRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.ListExistingTasks(ctx, &req)
			},
			"ExecuteCommand": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ExecuteCommandRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.ExecuteCommand(ctx, &req)
			},
		},
	})
}

type agenttaskClient struct {
	client *ttrpc.Client
}

func NewAgentTaskClient(client *ttrpc.Client) AgentTaskService {
	return &agenttaskClient{
		client: client,
	}
}

func (c *agenttaskClient) ListExistingTasks(ctx context.Context, req *ListExistingTasksRequest) (*ListExistingTasksResponse, error) {
	var resp ListExistingTasksResponse
	if err := c.client.Call(ctx, "AgentTask", "ListExistingTasks", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *agenttaskClient) ExecuteCommand(ctx context.Context, req *ExecuteCommandRequest) (*ExecuteCommandResponse, error) {
	var resp ExecuteCommandResponse
	if err := c.client.Call(ctx, "AgentTask", "ExecuteCommand", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
